// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package http

// NewRole defines model for NewRole.
type NewRole struct {
	// Name of the role
	Name string `json:"name"`

	// Type of the role
	Tag *string `json:"tag,omitempty"`
}

// Role defines model for Role.
type Role struct {
	// Unique id of the role
	Id int64 `json:"id"`

	// Name of the role
	Name string `json:"name"`

	// Type of the role
	Tag *string `json:"tag,omitempty"`
}

// Error defines model for error.
type Error = interface{}

// FindRolesParams defines parameters for FindRoles.
type FindRolesParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`
}

// CreateRoleJSONBody defines parameters for CreateRole.
type CreateRoleJSONBody = NewRole

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleJSONBody
