user:
  handler: bootstrap
  package:
    artifact: bin/user/bootstrap_user.zip
  events:
    - http:
        path: /user
        method: ANY
        cors: true
    - http:
        path: /user/{any+}
        method: ANY
        cors: true
  environment:
    MYSQL_HOST: ${file(./environment/${self:provider.stage}.yml):ENV_MYSQL_HOST}
    MYSQL_PORT: ${file(./environment/${self:provider.stage}.yml):ENV_MYSQL_PORT}
    MYSQL_USERNAME: ${file(./environment/${self:provider.stage}.yml):ENV_MYSQL_USERNAME}
    MYSQL_PASSWORD: ${file(./environment/${self:provider.stage}.yml):ENV_MYSQL_PASSWORD}
    MYSQL_DATABASE: ${file(./environment/${self:provider.stage}.yml):ENV_MYSQL_DATABASE}
